export enum FabricCAServerFlags {
  /*
   * Listening address of fabric-ca-server (default "0.0.0.0")
   */
  ADDRESS = "--address",
  /*
   * The user:pass for bootstrap admin which is required to build default config file
   */
  BOOT = "--boot",
  //   CA_CERTFILE = "--ca.certfile",
  //   CA_CHAINFILE = "--ca.chainfile",
  //   CA_KEYFILE = "--ca.keyfile",
  /**
   *  Certificate Authority name
   */
  CA_NAME = "--ca.name",
  //   CA_REENROLL_IGNORE_CERT_EXPIRY = "--ca.reenrollignorecertexpiry",
  //   CA_COUNT = "--cacount",
  //   CA_FILES = "--cafiles",
  //   CFG_AFFILIATIONS_ALLOW_REMOVE = "--cfg.affiliations.allowremove",
  //   CFG_IDENTITIES_ALLOW_REMOVE = "--cfg.identities.allowremove",
  //   CFG_IDENTITIES_PASSWORD_ATTEMPTS = "--cfg.identities.passwordattempts",
  //   CORS_ENABLED = "--cors.enabled",
  //   CORS_ORIGINS = "--cors.origins",
  //   CRL_EXPIRY = "--crl.expiry",
  //   CRL_SIZE_LIMIT = "--crlsizelimit",
  //   CSR_CN = "--csr.cn",
  //   CSR_HOSTS = "--csr.hosts",
  //   CSR_KEYREQUEST_ALGO = "--csr.keyrequest.algo",
  //   CSR_KEYREQUEST_REUSE_KEY = "--csr.keyrequest.reusekey",
  //   CSR_KEYREQUEST_SIZE = "--csr.keyrequest.size",
  //   CSR_SERIALNUMBER = "--csr.serialnumber",
  //   DB_DATASOURCE = "--db.datasource",
  //   DB_TLS_CERTFILES = "--db.tls.certfiles",
  //   DB_TLS_CLIENT_CERTFILE = "--db.tls.client.certfile",
  //   DB_TLS_CLIENT_KEYFILE = "--db.tls.client.keyfile",
  //   DB_TYPE = "--db.type",

  /**
   * Enable debug level logging (slows server)
   */
  DEBUG = "--debug",
  /**
   * Server's home directory (default "/etc/hyperledger/fabric-ca")
   */
  HOME = "--home",
  //   IDEMIX_CURVE = "--idemix.curve",
  //   IDEMIX_NONCE_EXPIRATION = "--idemix.nonceexpiration",
  //   IDEMIX_NONCE_SWIPE_INTERVAL = "--idemix.noncesweepinterval",
  //   IDEMIX_RHPOOLSIZE = "--idemix.rhpoolsize",
  //   INTERMEDIATE_ENROLLMENT_LABEL = "--intermediate.enrollment.label",
  //   INTERMEDIATE_ENROLLMENT_PROFILE = "--intermediate.enrollment.profile",
  //   INTERMEDIATE_ENROLLMENT_TYPE = "--intermediate.enrollment.type",
  //   INTERMEDIATE_PARENTSERVER_CANAME = "--intermediate.parentserver.caname",
  //   INTERMEDIATE_PARENTSERVER_URL = "--intermediate.parentserver.url",
  //   INTERMEDIATE_TLS_CERTFILES = "--intermediate.tls.certfiles",
  //   INTERMEDIATE_TLS_CLIENT_CERTFILE = "--intermediate.tls.client.certfile",
  //   INTERMEDIATE_TLS_CLIENT_KEYFILE = "--intermediate.tls.client.keyfile",
  //   LDAP_ATTRIBUTE_NAMES = "--ldap.attribute.names",
  //   LDAP_ENABLED = "--ldap.enabled",
  //   LDAP_GROUPFILTER = "--ldap.groupfilter",
  //   LDAP_TLS_CERTFILES = "--ldap.tls.certfiles",
  //   LDAP_TLS_CLIENT_CERTFILE = "--ldap.tls.client.certfile",
  //   LDAP_TLS_CLIENT_KEYFILE = "--ldap.tls.client.keyfile",
  //   LDAP_URL = "--ldap.url",
  //   LDAP_USERFILTER = "--ldap.userfilter",
  //   LOGLEVEL = "--loglevel",
  /**
   *  Listening port of fabric-ca-server (default 7054)
   */
  PORT = "--port",
  //   REGISTRY_MAX_ENROLLMENTS = "--registry.maxenrollments",
  //   TLS_CLIENTAUTH_CERTFILES = "--tls.clientauth.certfiles",
  //   TLS_CLIENTAUTH_TYPE = "--tls.clientauth.type",
  /**
   * Enable TLS on the listening port
   */
  TLS_ENABLED = "--tls.enabled",
  /**
   * PEM-encoded TLS certificate file for server's listening port (default "tls-cert.pem")
   */
  TLS_CERTFILE = "--tls.certfile",
  /**
   * PEM-encoded TLS key for server's listening port
   */
  TLS_KEYFILE = "--tls.keyfile",
}

//     --ca.certfile string                        PEM-encoded CA certificate file (default "ca-cert.pem")
//     --ca.chainfile string                       PEM-encoded CA chain file (default "ca-chain.pem")
//     --ca.keyfile string                         PEM-encoded CA key file
//     --ca.reenrollignorecertexpiry               Ignore Certificate Expiry for re-enroll
//     --cacount int                               Number of non-default CA instances
//     --cafiles strings                           A list of comma-separated CA configuration files
//     --cfg.affiliations.allowremove              Enables removal of affiliations dynamically
//     --cfg.identities.allowremove                Enables removal of identities dynamically
//     --cfg.identities.passwordattempts int       Number of incorrect password attempts allowed (default 10)
//     --cors.enabled                              Enable CORS for the fabric-ca-server
//     --cors.origins strings                      Comma-separated list of Access-Control-Allow-Origin domains
//     --crl.expiry duration                       Expiration for the CRL generated by the gencrl request (default 24h0m0s)
//     --crlsizelimit int                          Size limit of an acceptable CRL in bytes (default 512000)
//     --csr.cn string                             The common name field of the certificate signing request to a parent fabric-ca-server
//     --csr.hosts strings                         A list of comma-separated host names in a certificate signing request to a parent fabric-ca-server
//     --csr.keyrequest.algo string                Specify key algorithm
//     --csr.keyrequest.reusekey                   Reuse existing key during reenrollment
//     --csr.keyrequest.size int                   Specify key size
//     --csr.serialnumber string                   The serial number in a certificate signing request to a parent fabric-ca-server
//     --db.datasource string                      Data source which is database specific (default "fabric-ca-server.db")
//     --db.tls.certfiles strings                  A list of comma-separated PEM-encoded trusted certificate files (e.g. root1.pem,root2.pem)
//     --db.tls.client.certfile string             PEM-encoded certificate file when mutual authenticate is enabled
//     --db.tls.client.keyfile string              PEM-encoded key file when mutual authentication is enabled
//     --db.type string                            Type of database; one of: sqlite3, postgres, mysql (default "sqlite3")
// -h, --help                                      help for fabric-ca-server
//     --idemix.curve string                       Name of the curve among {'amcl.Fp256bn', 'gurvy.Bn254', 'amcl.Fp256Miraclbn'}, defaults to 'amcl.Fp256bn' (default "amcl.Fp256bn")
//     --idemix.nonceexpiration string             Duration after which a nonce expires (default "15s")
//     --idemix.noncesweepinterval string          Interval at which expired nonces are deleted (default "15m")
//     --idemix.rhpoolsize int                     Specifies revocation handle pool size (default 100)
//     --intermediate.enrollment.label string      Label to use in HSM operations
//     --intermediate.enrollment.profile string    Name of the signing profile to use in issuing the certificate
//     --intermediate.enrollment.type string       The type of enrollment request: 'x509' or 'idemix' (default "x509")
//     --intermediate.parentserver.caname string   Name of the CA to connect to on fabric-ca-server
// -u, --intermediate.parentserver.url string      URL of the parent fabric-ca-server (e.g. http://<username>:<password>@<address>:<port)
//     --intermediate.tls.certfiles strings        A list of comma-separated PEM-encoded trusted certificate files (e.g. root1.pem,root2.pem)
//     --intermediate.tls.client.certfile string   PEM-encoded certificate file when mutual authenticate is enabled
//     --intermediate.tls.client.keyfile string    PEM-encoded key file when mutual authentication is enabled
//     --ldap.attribute.names strings              The names of LDAP attributes to request on an LDAP search
//     --ldap.enabled                              Enable the LDAP client for authentication and attributes
//     --ldap.groupfilter string                   The LDAP group filter for a single affiliation group (default "(memberUid=%s)")
//     --ldap.tls.certfiles strings                A list of comma-separated PEM-encoded trusted certificate files (e.g. root1.pem,root2.pem)
//     --ldap.tls.client.certfile string           PEM-encoded certificate file when mutual authenticate is enabled
//     --ldap.tls.client.keyfile string            PEM-encoded key file when mutual authentication is enabled
//     --ldap.url string                           LDAP client URL of form ldap://adminDN:adminPassword@host[:port]/base
//     --ldap.userfilter string                    The LDAP user filter to use when searching for users (default "(uid=%s)")
//     --loglevel string                           Set logging level (info, warning, debug, error, fatal, critical)
//     --registry.maxenrollments int               Maximum number of enrollments; valid if LDAP not enabled (default -1)
//     --tls.clientauth.certfiles strings          A list of comma-separated PEM-encoded trusted certificate files (e.g. root1.pem,root2.pem)
//     --tls.clientauth.type string                Policy the server will follow for TLS Client Authentication. (default "noclientcert")
